# Generated by Django 4.2.2 on 2023-12-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='topic',
        ),
        migrations.AddField(
            model_name='feedback',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
